### ISSUE TITLE
No-GUI support

### ISSUE THREAD

**Issue by kovalovme** [aliesbelik/jmeter-amqp-plugin#32]
Hello,
Does this package support no-gui jmeter execution?
Local gui Jmeter works fine.
I'm having issues using it within docker container `justb4/jmeter:5.4`

**Comment by kovalovme** [comment]
Execution logs:

```
2022-11-03 14:45:06,756 INFO o.a.j.e.StandardJMeterEngine: Running the test!
2022-11-03 14:45:06,761 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2022-11-03 14:45:06,761 INFO o.a.j.s.SampleEvent: List of sample_variables: []
2022-11-03 14:45:06,769 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must contain the string: '.functions.'
2022-11-03 14:45:06,769 INFO o.a.j.e.u.CompoundVariable: Note: Function class names must not contain the string: '.gui.'
2022-11-03 14:45:07,385 INFO o.a.j.JMeter: Running test (1667483107385)
2022-11-03 14:45:07,496 INFO o.a.j.e.StandardJMeterEngine: Starting ThreadGroup: 1 : Thread Group
2022-11-03 14:45:07,496 INFO o.a.j.e.StandardJMeterEngine: Starting 1 threads for group Thread Group.
2022-11-03 14:45:07,496 INFO o.a.j.e.StandardJMeterEngine: Thread will continue on error
2022-11-03 14:45:07,496 INFO o.a.j.t.ThreadGroup: Starting thread group... number=1 threads=1 ramp-up=1 delayedStart=false
2022-11-03 14:45:07,504 INFO o.a.j.t.ThreadGroup: Started thread group number 1
2022-11-03 14:45:07,504 INFO o.a.j.e.StandardJMeterEngine: All thread groups have been started
2022-11-03 14:45:07,544 INFO o.a.j.t.JMeterThread: Thread started: Thread Group 1-1
2022-11-03 14:45:07,545 INFO c.z.j.p.a.AMQPSampler: AMQPSampler.threadStarted called
2022-11-03 14:45:07,545 INFO c.z.j.p.a.AMQPSampler: AMQPSampler.threadStarted called
2022-11-03 14:45:07,551 INFO o.a.j.s.SampleResult: Note: Sample TimeStamps are START times
2022-11-03 14:45:07,551 INFO o.a.j.s.SampleResult: sampleresult.default.encoding is set to ISO-8859-1
2022-11-03 14:45:07,551 INFO o.a.j.s.SampleResult: sampleresult.useNanoTime=true
2022-11-03 14:45:07,551 INFO o.a.j.s.SampleResult: sampleresult.nanoThreadSleep=5000
2022-11-03 14:45:07,552 INFO c.z.j.p.a.AMQPSampler: Creating channel (replaced actual data):5672
2022-11-03 14:45:07,553 INFO c.z.j.p.a.AMQPSampler: RabbitMQ ConnectionFactory using:
	 virtual host: (replaced actual data)
	 host: (replaced actual data)
	 port: 5672
	 username: (replaced actual data)
	 password: (replaced actual data)
	 timeout: 1000
	 heartbeat: 60
in com.zeroclue.jmeter.protocol.amqp.AMQPPublisher@4fd78700
2022-11-03 14:45:08,587 WARN c.z.j.p.a.AMQPPublisher: null
java.lang.NullPointerException: null
	at com.zeroclue.jmeter.protocol.amqp.AMQPPublisher.sample(AMQPPublisher.java:106) [jmeter-amqp-plugin-0.2.0.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
2022-11-03 14:45:08,597 INFO c.z.j.p.a.AMQPSampler: Creating channel (replaced actual data):5672
2022-11-03 14:45:08,597 INFO c.z.j.p.a.AMQPSampler: RabbitMQ ConnectionFactory using:
	 virtual host: (replaced actual data)
	 host: (replaced actual data)
	 port: 5672
	 username: (replaced actual data)
	 password: (replaced actual data)
	 timeout: 1000
	 heartbeat: 60
in com.zeroclue.jmeter.protocol.amqp.AMQPConsumer@504e9a8a
2022-11-03 14:45:09,600 ERROR c.z.j.p.a.AMQPConsumer: Failed to initialize channel
java.lang.NullPointerException: null
	at com.zeroclue.jmeter.protocol.amqp.AMQPConsumer.initChannel(AMQPConsumer.java:354) ~[jmeter-amqp-plugin-0.2.0.jar:?]
	at com.zeroclue.jmeter.protocol.amqp.AMQPConsumer.sample(AMQPConsumer.java:84) [jmeter-amqp-plugin-0.2.0.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
2022-11-03 14:45:09,603 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2022-11-03 14:45:09,603 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2022-11-03 14:45:09,603 INFO c.z.j.p.a.AMQPSampler: AMQPSampler.threadFinished called
2022-11-03 14:45:09,604 INFO c.z.j.p.a.AMQPSampler: AMQPSampler.threadFinished called
2022-11-03 14:45:09,604 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2022-11-03 14:45:09,605 INFO o.a.j.r.Summariser: summary =      2 in 00:00:02 =    0.9/s Avg:     5 Min:     0 Max:    11 Err:     2 (100.00%)
```
